spring.application.name=Learning2026
//server.port=8088


# ===============================
# PostgreSQL Database Configuration
# ===============================
#
#//spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/Generate
spring.datasource.url=jdbc:postgresql://${dpg-da457tajobas73aai0r0-a}:${5432}/${learning2026}
spring.datasource.username=${learninguser}
spring.datasource.password=${secret}


#spring.datasource.url=jdbc:postgresql://postgres:5432/Learning2026
##spring.datasource.url=jdbc:postgresql://localhost:5432/Learning2026
#
#spring.datasource.username=postgres
#spring.datasource.password=sabzar

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
